pipeline:
  name: NGPipeAuto5S0lgd0ZmO
  identifier: NGPipeAuto5S0lgd0ZmO
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 1m
        tags: {}
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: account.stage_4
          versionLabel: v4
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: t1
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                  - step:
                      identifier: t8
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
