pipeline:
  name: ParentPipeline1GlzyKD6ew
  identifier: ParentPipeline1GlzyKD6ew
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_Rhqte
          project: SimplifiedGitSync_Do_Not_Delete