pipeline:
  name: ParentPipelineWSec68fk4O
  identifier: ParentPipelineWSec68fk4O
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_LqNvC
          project: SimplifiedGitSync_Do_Not_Delete