pipeline:
  name: pl_auto_pipeline_i0koH
  identifier: pl_auto_pipeline_i0koH
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: stage2
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_3JFRF
          project: SimplifiedGitSync_Do_Not_Delete
        description: ""
        tags: {}
