pipeline:
  name: remotePipeline
  identifier: remotePipeline
  projectIdentifier: NGPipeAutoExpressionsC4xi689Z7X
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: cs1
        identifier: cs1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  timeout: 10m
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo hi
                    environmentVariables: []
                    outputVariables: []
        tags: {}
