pipeline:
  name: pl_auto_pipeline_X3jtg
  identifier: pl_auto_pipeline_X3jtg
  template:
    templateRef: account.pl_auto_template_x5MF3
    versionLabel: v3
    templateInputs:
      stages:
        - stage:
            identifier: q1
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: a1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync